### PR TITLE
fixes to this context in some anonimous functions, also removed unused variables

### PR DESCRIPTION
**Pull request by okonovalenko**
when calling this._controller in some functions this context was not passed in, so was getting this._controller undefined exceptions, especially when trying to place combo order.

### CODE REVIEW

**Comment by pilwon** [comment]
@okonovalenko `.DS_Store` and `.idea` files are platform/environment-specific and the global git ignore file is where they should be instead of a project-specific git ignore file. I'll merge once this is removed from your PR.

**Comment by okonovalenko** [comment]
good point, done!

**Comment by pilwon** [comment]
@okonovalenko Could we leave `.gitignore` untouched by this PR? Thanks-

**Comment by okonovalenko** [comment]
sure, do u want me to do something about it?

**Comment by pilwon** [comment]
@okonovalenko Click on `Files Changed` tab then you'll see `.gitignore` is still being touched by your PR.

**Comment by okonovalenko** [comment]
done

**Comment by pilwon** [comment]
@okonovalenko Thanks for your PR-

**Pull request merged**
