### PR TITLE
supported other currencies for forex contract.

### PR DESCRIPTION
**Pull request by yuanzhanghu**
Added RUB/TRY/ZAR

### CODE REVIEW

**Comment by pilwon** [comment]
@yuanzhanghu I remember the ordering of this string array was important. Are you sure these additional ones go in that exact order?

**Comment by yuanzhanghu** [comment]
Yeah, you are right,  haven't taken care of that.    Just checked symbols, we have USDRUB/EURRUB/USDTRY/EURTRY/TRYJPY/USDZAR/EURZAR/ZARJPY,  so the sequence should be:   EUR>USD>ZAR/TRY>JPY>RUB.

**Comment by pilwon** [comment]
@yuanzhanghu Thanks for your PR-

**Comment by yuanzhanghu** [comment]
thanks for quick merge.

**Comment by pilwon** [comment]
Published as v0.1.8

**Pull request merged**
